### This file contains HTTP requests for testing the portfolio management API.

###
POST http://localhost:8081/api/portfolios
Content-Type: application/json

{
  "ownerName": "Rachel Green"
}

> {%
    client.global.set("portfolioId", response.body.id);
%}

###
GET http://localhost:8081/api/portfolios/{{portfolioId}}

###
POST http://localhost:8081/api/portfolios/{{portfolioId}}/deposits
Content-Type: application/json

{
  "amount": "1000000"
}

###
POST http://localhost:8081/api/portfolios/{{portfolioId}}/withdrawals
Content-Type: application/json

{
  "amount": "900000"
}

###
POST http://localhost:8081/api/portfolios/{{portfolioId}}/purchases
Content-Type: application/json

{
  "ticker": "GOOGL",
  "quantity": 20
}

###
POST http://localhost:8081/api/portfolios/{{portfolioId}}/purchases
Content-Type: application/json

{
  "ticker": "AAPL",
  "quantity": 10
}

###
POST http://localhost:8081/api/portfolios/{{portfolioId}}/sales
Content-Type: application/json

{
  "ticker": "AAPL",
  "quantity": 10
}

###
GET http://localhost:8081/api/portfolios/{{portfolioId}}/transactions

###
GET http://localhost:8081/api/portfolios/{{portfolioId}}/holdings

